### ISSUE TITLE
Login error occurred! 

### ISSUE THREAD

**Issue by Villelmo** [Spikeedoo/SnooKey#14]
Traceback (most recent call last):   File "/home/lulu/SnooKey/snookey.py", line 143, in <module>     rpan_subreddits_full = subreddit_check.json()["data"] KeyError: 'data'

**Comment by Spikeedoo** [comment]
@Villelmo try cloning the repo with my latest patch and let me know if this error is still popping up. If it is I will try to track it down further.

**Comment by Villelmo** [comment]
I get the following error: 

```
Welcome to SnooKey v2.0
Waiting for access token...
Working token found!  Continuing...
Traceback (most recent call last):
  File "/home/lulu/SnooKey/snookey.py", line 128, in <module>
    rpan_subreddits_full = subreddit_check.json()["data"]
KeyError: 'data'

```
Where is saved the token?

**Comment by Villelmo** [comment]
> I get the following error:
> 
> ```
> Welcome to SnooKey v2.0
> Waiting for access token...
> Working token found!  Continuing...
> Traceback (most recent call last):
>   File "/home/lulu/SnooKey/snookey.py", line 128, in <module>
>     rpan_subreddits_full = subreddit_check.json()["data"]
> KeyError: 'data'
> ```
> 
> Where is saved the token?
